from datetime import datetime, timezone
from pathlib import Path

from .. import __version__
from ..schemas.release_notes import ReleaseNotes
from .base import BaseFormatter


class MarkdownFormatter(BaseFormatter):
    def __init__(self, output_dir: str = "./release-notes", **_: object):
        self.output_dir = output_dir

    async def write(self, notes: ReleaseNotes) -> str:
        Path(self.output_dir).mkdir(parents=True, exist_ok=True)
        path = Path(self.output_dir) / f"{notes.version}.md"
        path.write_text(render_markdown(notes))
        return str(path)


def render_markdown(notes: ReleaseNotes) -> str:
    date = datetime.now(timezone.utc).date().isoformat()
    return "\n".join(
        [
            f"# Release Notes — {notes.version} ({date})",
            "",
            "## ✨ Features",
            _section(notes.features, "No new features."),
            "",
            "## 🐛 Bug Fixes",
            _section(notes.bug_fixes, "No bug fixes."),
            "",
            "## 🔧 Improvements",
            _section(notes.improvements, "No improvements."),
            "",
            "## ⚠️ Breaking Changes",
            _section(notes.breaking_changes, "No breaking changes."),
            "",
            "---",
            f"*Generated by releasenotes-agent {__version__} using {notes.llm_provider}/{notes.llm_model}*",
            f"*Coverage: {notes.coverage_pct:.0%} of closed tickets | Run ID: {notes.run_id}*",
            "",
        ]
    )


def _section(lines: list[str], empty: str) -> str:
    return "\n".join(lines) if lines else empty
